# for `dev` branch
-
  version: 1.0.0-alpha-{build}
  branches:
    only:
    - dev
  skip_tags: true
  os: Visual Studio 2015
  configuration:
  - Debug
  platform: Any CPU
  environment:
    project_name_core: scissorhands.core
    project_name_helpers: scissorhands.helpers
    project_name_themes: scissorhands.themes
    project_name_services: scissorhands.services
    project_name_webapp: scissorhands.webapp
  install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: dnvm install 1.0.0-rc1-update1
  before_build:
  - cmd: dnu restore -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
  build:
    verbosity: detailed
  test_script:
  - cmd: dnu restore -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
  - ps: ./run-tests.ps1

# for `master` branch
-
  version: 1.0.0-alpha-{build}
  branches:
    only:
    - master
  skip_tags: true
  os: Visual Studio 2015
  configuration:
  - Release
  platform: Any CPU
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: 1.0.0.{build}
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    project_name_core: scissorhands.core
    project_name_helpers: scissorhands.helpers
    project_name_themes: scissorhands.themes
    project_name_services: scissorhands.services
    project_name_webapp: scissorhands.webapp
    github_auth_token:
      secure: 3tp7rCl4cvk/WDYBaeodIlmalNiYVWQYxE1wmVU7aMbkMKP0WtlMjjOU2yhX0D4n
  install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: dnvm install 1.0.0-rc1-update1
  before_build:
  - cmd: dnu restore -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
  - ps: ./run-project-versioning.ps1
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: detailed
  test_script:
  - cmd: dnu restore -f https://www.myget.org/F/aspnet-contrib/api/v3/index.json
  - ps: ./run-tests.ps1
  artifacts:
  - path: artifacts\bin\$(project_name_core)\$(configuration)\*.nupkg
    name: core
  - path: artifacts\bin\$(project_name_helpers)\$(configuration)\*.nupkg
    name: helpers
  - path: artifacts\bin\$(project_name_themes)\$(configuration)\*.nupkg
    name: themes
  - path: artifacts\bin\$(project_name_services)\$(configuration)\*.nupkg
    name: services
  - path: artifacts\bin\$(project_name_webapp)\$(configuration)\*.nupkg
    name: webapp
  deploy:
  - provider: NuGet
    api_key:
      secure: +nwrSNmydF+453m3jZAS/qb5D2KAgs1ZXQDhCE/AjPvYo1IRDGI5pj3PFriX7ADd
    artifact: core
    on:
      branch: master
      platform: Any CPU
      configuration: Release
      appveyor_repo_tag: true
      appveyor_repo_tag_name: release-core
  - provider: GitHub
    tag: $(project_name_core)-v$(appveyor_build_version)
    description: $(project_name_core)-v$(appveyor_build_version) has been released
    auth_token:
      secure: 3tp7rCl4cvk/WDYBaeodIlmalNiYVWQYxE1wmVU7aMbkMKP0WtlMjjOU2yhX0D4n
    artifact: core
    on:
      branch: master
      platform: Any CPU
      configuration: Release
      appveyor_repo_tag: true
      appveyor_repo_tag_name: release-core
  after_deploy:
  - cmd: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_auth_token):x-oauth-basic@github.com`n"
  - cmd: git push --delete origin release-core
