<Project>
  <PropertyGroup>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="bunit" Version="2.*" />
    <PackageVersion Include="coverlet.collector" Version="10.*" />
    <PackageVersion Include="Markdig" Version="1.*" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.*" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.*" />
    <PackageVersion Include="NSubstitute" Version="6.*" />
    <PackageVersion Include="Scrutor" Version="7.*" />
    <PackageVersion Include="Shouldly" Version="4.*" />
    <PackageVersion Include="System.Reactive" Version="7.*" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.*" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.*" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.*" />
    <PackageVersion Include="xunit.v3" Version="4.*" />
    <PackageVersion Include="YamlDotNet" Version="18.*" />
  </ItemGroup>
</Project>
