<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <LangVersion>latest</LangVersion>

    <AssemblyName>ScissorHands.Web</AssemblyName>
    <RootNamespace>ScissorHands.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <PackageReference Include="Markdig" Version="0.*" />
    <PackageReference Include="System.Reactive" Version="6.*" />
    <PackageReference Include="YamlDotNet" Version="16.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScissorHands.Core\ScissorHands.Core.csproj" />
    <ProjectReference Include="..\ScissorHands.Plugin\ScissorHands.Plugin.csproj" />
    <ProjectReference Include="..\ScissorHands.Theme\ScissorHands.Theme.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions/" />
  </ItemGroup>

</Project>
