<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <PackageDescription>The ScissorHands.NET static site generation engine for Markdown content and Razor themes.</PackageDescription>
    <PackageTags>scissorhands;web;static-site</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <PackageReference Include="Markdig" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScissorHands.Core\ScissorHands.Core.csproj" />
    <ProjectReference Include="..\ScissorHands.Plugin\ScissorHands.Plugin.csproj" />
    <ProjectReference Include="..\ScissorHands.Theme\ScissorHands.Theme.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="contents/**/*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="themes/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
