name: Bug Report
description: Create a report to help us improve
title: '[Bug]: '
labels: [ 'triage' ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: 'Steps to reproduce the behavior:'
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: 'Which version of the package are you using?'
      placeholder: e.g. 1.0.0, 2.1.3, 3.0.0-beta
    validations:
      required: true

  - type: textarea
    id: desktop-environment
    attributes:
      label: Desktop Environment
      description: 'Please complete the following information:'
      placeholder: |
        - OS: [e.g. Windows, MacOS ]
        - Browser [e.g. chrome, edge, safari]
        - Version [e.g. 11, 26.2]
      value: |
        - OS: [e.g. Windows, MacOS ]
        - Browser [e.g. chrome, edge, safari]
        - Version [e.g. 11, 26.2]
    validations:
      required: false

  - type: textarea
    id: mobile-environment
    attributes:
      label: Mobile Environment
      description: 'Please complete the following information:'
      placeholder: |
       - Device: [e.g. iPhone 17 Pro Max, Pixel 10 Pro XL ]
       - OS: [e.g. iOS, Android ]
       - Browser [e.g. chrome, edge, safari]
       - Version [e.g. 26.2, 16]
      value: |
       - Device: [e.g. iPhone 17 Pro Max, Pixel 10 Pro XL ]
       - OS: [e.g. iOS, Android ]
       - Browser [e.g. chrome, edge, safari]
       - Version [e.g. 26.2, 16]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Add any other context about the problem here.
    validations:
      required: false
