<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <LangVersion>latest</LangVersion>

    <AssemblyName>ScissorHands.Theme.MinimalBlog</AssemblyName>
    <RootNamespace>ScissorHands.Theme.MinimalBlog</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\ScissorHands.Theme\ScissorHands.Theme.csproj" />
  </ItemGroup>

</Project>
