<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <LangVersion>latest</LangVersion>

    <AssemblyName>ScissorHands.Core</AssemblyName>
    <RootNamespace>ScissorHands.Core</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>

    <PackageId>ScissorHands.Core</PackageId>
    <Version>1.0.0</Version>

    <Title>ScissorHands.Core</Title>
    <Authors>Justin Yoo</Authors>
    <Company>GetScissorHands</Company>
    <Product>ScissorHands.Core</Product>
    <Summary>ScissorHands.Core: Building a static website using .NET</Summary>
    <Description>This is a library that builds a static website using .NET</Description>
    <Copyright>© GetScissorHands. All rights reserved.</Copyright>
    <Owners>justinyoo</Owners>

    <PackageProjectUrl>https://github.com/getscissorhands/Scissorhands.NET</PackageProjectUrl>
    <PackageIcon>ScissorHands.png</PackageIcon>
    <PackageIconUrl>https://raw.githubusercontent.com/getscissorhands/Scissorhands.NET/refs/heads/vnext/assets/ScissorHands.png</PackageIconUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>scissorhands;core;static-site</PackageTags>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>

    <RepositoryUrl>https://github.com/getscissorhands/Scissorhands.NET</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\assets\ScissorHands.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
