<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <LangVersion>latest</LangVersion>

    <AssemblyName>ScissorHands.Plugin</AssemblyName>
    <RootNamespace>ScissorHands.Plugin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ScissorHands.Core\ScissorHands.Core.csproj" />
  </ItemGroup>

</Project>
