name: Build and Test

on:
  push:
    branches:
    - main
    - release/*
    - feature/*
    - hotfix/*

jobs:
  build_and_test:
    name: Build and test
    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Clear NuGet local cache
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        dotnet nuget locals all --clear

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dotnet restore .

    - name: Build solution
      shell: pwsh
      run: |
        dotnet build . -c Debug -v minimal

    - name: Run unit tests
      shell: pwsh
      run: |
        dotnet test . -c Debug
